# Render Blueprint - DÃ©ploiement Valentine App
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: valentine-app
    runtime: node
    buildCommand: "bash build.sh"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
