# Render Blueprint - DÃ©ploiement Valentine App
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: valentine-app
    runtime: node

    buildCommand: "npm install"
    startCommand: "node server.js"

    envVars:
      - key: NODE_VERSION
        value: 18
